const majors = {
  0: "Accountancy - BUS",
  1: "Acting - FAA",
  2: "Actuarial Science - LAS",
  3: "Advertising - COM",
  4: "Aerospace Engineering - ENG",
  5: "African American Studies - LAS",
  6: "Agri-Accounting - ACES",
  7: "Agribusiness, Markets &amp; Management - ACES",
  8: "Agricultural &amp; Biological Engineering - ACES",
  9: "Agricultural &amp; Biological Engineering - ENG",
  10: "Agricultural &amp; Consumer Economics - ACES",
  11: "Agricultural Communications - ACES",
  12: "Agricultural Leadership Education - ACES",
  13: "Agricultural Science Education - ACES",
  14: "Agroecology - ACES",
  15: "Animal Sciences - ACES",
  16: "Anthropology - LAS",
  17: "Architectural Studies - FAA",
  18: "Art Education (K-12) - FAA",
  19: "Art History - FAA",
  20: "Asian American Studies - LAS",
  21: "Astronomy - LAS",
  22: "Atmospheric Sciences - LAS",
  23: "Audiology - AHS",
  24: "Biochemistry - LAS",
  25: "Bioengineering - ENG",
  26: "Biological Sciences (Crop Sciences) - ACES",
  27: "Biology - LAS",
  28: "Business Process Management - BUS",
  29: "Chemical &amp; Biomolecular Engineering - LAS",
  30: "Chemistry - LAS",
  31: "Child &amp; Adolescent Development - ACES",
  32: "Civil Engineering - ENG",
  33: "Classical Archaeology^ - LAS",
  34: "Classical Civilization^ - LAS",
  35: "Classics - LAS",
  36: "Communication - LAS",
  37: "Community Health - AHS",
  38: "Companion Animal &amp; Equine Science - ACES",
  39: "Comparative &amp; World Literature - LAS",
  40: "Computer Engineering - ENG",
  41: "Computer Science - ENG",
  42: "Computer Science &amp; Anthropology - LAS",
  43: "Computer Science &amp; Astronomy - LAS",
  44: "Computer Science &amp; Chemistry - LAS",
  45: "Computer Science &amp; Linguistics - LAS",
  46: "Consumer Economics &amp; Finance - ACES",
  47: "Costume Design &amp; Technology - FAA",
  48: "Crafts: Ceramics - FAA",
  49: "Crafts: Metals - FAA",
  50: "Creative Writing - LAS",
  51: "Crop Agribusiness - ACES",
  52: "Crop Sciences - ACES",
  53: "Crops - ACES",
  54: "Cultural Linguistic Diversity - AHS",
  55: "Dance - FAA",
  56: "Dietetics - ACES",
  57: "Early Childhood Education (Birth-Grade 2) - EDU",
  58: "Earth, Society &amp; Environmental Sustainability - LAS",
  59: "East Asian Languages &amp; Cultures - LAS",
  60: "Economics - LAS",
  61: "Electrical Engineering - ENG",
  62: "Elementary Education (Grades 1-6) - EDU",
  63: "Engineering Mechanics - ENG",
  64: "Engineering Physics - ENG",
  65: "English - LAS",
  66: "Entrepreneurship - BUS",
  67: "Environmental Economics &amp; Policy - ACES",
  68: "Family Studies - ACES",
  69: "Farm Management - ACES",
  70: "Finance - BUS",
  71: "Finance in Agri-Business - ACES",
  72: "Financial Planning - ACES",
  73: "Fish &amp; Wildlife Conservation - ACES",
  74: "Food Science - ACES",
  75: "Food Science &amp; Human Nutrition - ACES",
  76: "French - LAS",
  77: "Gender &amp; Women&#039;s Studies - LAS",
  78: "Geography &amp; Geographic Information Science - LAS",
  79: "Geology - LAS",
  80: "Germanic Languages &amp; Literature - LAS",
  81: "Global Change &amp; Landscape Dynamics - ACES",
  82: "Global Studies - LAS",
  83: "Graphic Design - FAA",
  84: "Greek^ - LAS",
  85: "Health Education &amp; Promotion - AHS",
  86: "Health Planning &amp; Administration - AHS",
  87: "Health Sciences, Interdisciplinary  - AHS",
  88: "History - LAS",
  89: "History of Art - LAS",
  90: "Horticultural Food Systems - ACES",
  91: "Hospitality Management - ACES",
  92: "Human Development &amp; Family Studies - ACES",
  93: "Human Dimensions of the Environment - ACES",
  94: "Human Nutrition - ACES",
  95: "Industrial Design - FAA",
  96: "Industrial Engineering - ENG",
  97: "Information Systems &amp; Information Technology - BUS",
  98: "Integrative Biology - LAS",
  99: "Interdisciplinary Studies - LAS",
  100: "International Business - BUS",
  101: "Italian - LAS",
  102: "Jazz Studies - FAA",
  103: "Jewish Studies - LAS",
  104: "Journalism - COM",
  105: "Kinesiology - AHS",
  106: "Kinesiology - Physical Education (K-12) - AHS",
  107: "Landscape Architecture  - FAA",
  108: "Latin^ - LAS",
  109: "Latin American Studies - LAS",
  110: "Latina/Latino Studies - LAS",
  111: "Learning &amp; Education Studies - EDU",
  112: "Lighting Design - FAA",
  113: "Linguistics - LAS",
  114: "Management - BUS",
  115: "Marketing - BUS",
  116: "Materials Science &amp; Engineering - ENG",
  117: "Mathematics - LAS",
  118: "Mathematics &amp; Computer Science - LAS",
  119: "Mechanical Engineering - ENG",
  120: "Media &amp; Cinema Studies - COM",
  121: "Medieval Civilization - LAS",
  122: "Middle Grades Education (Grades 5-8) - EDU",
  123: "Molecular &amp; Cellular Biology - LAS",
  124: "Music - FAA",
  125: "Music Composition Theory - FAA",
  126: "Music Education (K-12) - FAA",
  127: "Music Instrumental Performance - FAA",
  128: "Music Open Studies - FAA",
  129: "Music Voice Performance - FAA",
  130: "Musicology - FAA",
  131: "Natural Resources &amp; Environmental Sciences - ACES",
  132: "Neuroscience of Communication - AHS",
  133: "New Media - FAA",
  134: "Nuclear, Plasma &amp; Radiological Engineering - ENG",
  135: "Nursing^^ - NUR",
  136: "Painting - FAA",
  137: "Philosophy - LAS",
  138: "Photography - FAA",
  139: "Physics - LAS",
  140: "Plant Biotechnology &amp; Molecular Biology - ACES",
  141: "Plant Protection  - ACES",
  142: "Policy, International Trade &amp; Development - ACES",
  143: "Political Science - LAS",
  144: "Portuguese - LAS",
  145: "Psychology - LAS",
  146: "Public Policy &amp; Law - ACES",
  147: "Recreation Management - AHS",
  148: "Recreation, Sport &amp; Tourism - AHS",
  149: "Rehabilitation Studies - AHS",
  150: "Religion - LAS",
  151: "Resource Conservation &amp; Restoration Ecology - ACES",
  152: "Russian, East European &amp; Eurasian Studies - LAS",
  153: "Scenic Design - FAA",
  154: "Scenic Technology - FAA",
  155: "Science, Pre-Veterinary &amp; Medical - ACES",
  156: "Sculpture - FAA",
  157: "Secondary Education - LAS",
  158: "Secondary Education: Agricultural - ACES",
  159: "Secondary Education: Biology - LAS",
  160: "Secondary Education: Chemistry - LAS",
  161: "Secondary Education: Earth Science - LAS",
  162: "Secondary Education: English  - LAS",
  163: "Secondary Education: Mathematics - LAS",
  164: "Secondary Education: Physics - LAS",
  165: "Secondary Education: Social Studies - LAS",
  166: "Slavic Studies - LAS",
  167: "Social Work - SSW",
  168: "Sociology - LAS",
  169: "Sound Design &amp; Technology - FAA",
  170: "Spanish - LAS",
  171: "Special Education - EDU",
  172: "Speech &amp; Hearing Science - AHS",
  173: "Speech Language Pathology - AHS",
  174: "Sport Management - AHS",
  175: "Stage Management - FAA",
  176: "Statistics - LAS",
  177: "Statistics &amp; Computer Science - LAS",
  178: "Supply Chain Management - BUS",
  179: "Systems Engineering and Design (formerly General Engineering) - ENG",
  180: "Teacher Education: Art (K-12) - FAA",
  181: "Teacher Education: French (K-12) - LAS",
  182: "Teacher Education: German (K-12) - LAS",
  183: "Teacher Education: Japanese (K-12) - LAS",
  184: "Teacher Education: Kinesiology - Physical Education (K-12) - AHS",
  185: "Teacher Education: Latin (K-12) - LAS",
  186: "Teacher Education: Mandarin Chinese (K-12) - LAS",
  187: "Teacher Education: Spanish (K-12) - LAS",
  188: "Technical Systems Management - ACES",
  189: "Technology &amp; Management (Animal Sciences) - ACES",
  190: "Theatre - FAA",
  191: "Theatre Studies - FAA",
  192: "Tourism Management - AHS",
  193: "Undeclared - DGS",
  194: "Urban Studies &amp; Planning - FAA"
};

export default majors;
